"""create assets table

Revision ID: afb265f18b4c
Revises: 
Create Date: 2026-09-27 15:29:01.423331

"""
from typing import Sequence, Union

from alembic import op
import pgvector.sqlalchemy
import sqlalchemy as sa


revision: str = 'afb265f18b4c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # pgvector type is required by the embedding column below.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_path', sa.Text(), nullable=False),
    sa.Column('relative_path', sa.String(length=1024), nullable=False),
    sa.Column('file_type', sa.Enum('image', 'video', 'pdf', 'other', name='asset_file_type'), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', 'skipped', 'duplicate', 'unsupported', name='asset_status'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('processing_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('relative_path')
    )
    op.create_index(op.f('ix_assets_file_hash'), 'assets', ['file_hash'], unique=False)
    op.create_index(op.f('ix_assets_file_type'), 'assets', ['file_type'], unique=False)
    op.create_index(op.f('ix_assets_modified_at'), 'assets', ['modified_at'], unique=False)
    op.create_index(op.f('ix_assets_status'), 'assets', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assets_status'), table_name='assets')
    op.drop_index(op.f('ix_assets_modified_at'), table_name='assets')
    op.drop_index(op.f('ix_assets_file_type'), table_name='assets')
    op.drop_index(op.f('ix_assets_file_hash'), table_name='assets')
    op.drop_table('assets')
    sa.Enum(name='asset_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='asset_file_type').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
